version: "3.9"
services:
  builder:
    image: das-api/builder
    build:
      context: .
      dockerfile: Builder.Dockerfile
    environment:
      GIT_VERSION: 2.43.0


  accounts-backfiller:
    build:
      context: .
      dockerfile: Ops.Dockerfile
    depends_on:
      - builder
      - redis
    restart: always
    environment:
      RUST_LOG: error
      RUST_BACKTRACE: 1
    command:
      - /bin/sh
      - -c
      - |
        /usr/src/app/das-ops account program HivezrprVqHR6APKKQkkLHmUG8waZorXexEBRZWh5LRm,ChRCtrG7X5kb9YncA4wuyD68DXXL8Szt3zBCCGiioBTg,CrncyaGmZfWvpxRcpHEkSrqeeyQsdn4MAedo9KuARAc4,RSCR7UoY65mDMK8z2eCBvFmj4HSepGEY9ZjdCTiUDUA,B4DxK2DhseG2ieSqckSoSvfUbYRz6hbNfXeWwmF7dm4h,MiNESdRXUSmWY7NkAKdW9nMkjJZCaucguY3MDvkSmr6,HuntaX1CmUt5EByyFPE8pMf13SpvezybmMTtjmpmGmfj,Gui1D2TnmAqakeHfp4NNZCcpqawNVgmJxT9JBUqXgyoD --messenger-redis-url redis://redis:6379 --solana-rpc-url ${SOLANA_RPC} || echo "failed backfilling"
        echo "Done"
        sleep 6h
    logging:
      driver: "json-file"
      options:
        max-size: 200k
        max-file: 10
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  transactions-backfiller:
    build:
      context: .
      dockerfile: Ops.Dockerfile
    depends_on:
      - builder
      - db
      - migrator
      - redis
    restart: always
    volumes:
      - ./solana-test-validator-geyser-config/config-ingester-backfill.yml:/config.yml
    environment:
      RUST_LOG: error
      RUST_BACKTRACE: 1
    command:
      - /bin/sh
      - -c
      - |
        /usr/src/app/das-ops bubblegum backfill --only-honeycomb --database-url postgres://solana:${DB_PASSWORD}@db/solana --messenger-redis-url redis://redis:6379 --solana-rpc-url ${SOLANA_RPC} --ignore-bgum || echo "failed backfilling"
        echo "Done"
        sleep 6h
    logging:
      driver: "json-file"
      options:
        max-size: 200k
        max-file: 10
    extra_hosts:
      - "host.docker.internal:host-gateway"


  api:
    depends_on:
      - migrator
      - builder
    restart: always
    environment:
      RUST_LOG: error
      APP_DATABASE_URL: postgres://solana:${DB_PASSWORD}@db/solana
      APP_SERVER_PORT: 9090
    build:
      context: .
      dockerfile: Api.Dockerfile
    ports:
      - ${API_PORT}:9090

  proxy:
    environment:
      RUST_LOG: error
    build:
      context: .
      dockerfile: Proxy.Dockerfile
    volumes:
      - ./metaplex-rpc-proxy/envoy-compose.yaml:/etc/envoy.yaml
    ports:
      - ${PROXY_PORT}:9091
    extra_hosts:
      - "host.docker.internal:host-gateway"

  
  redis:
    image: "redis:7.0.0"
  
  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - ${REDIS_COMMANDER_PORT}:8081
  

  migrator:
    depends_on:
      - db
      - builder
    environment:
      DATABASE_URL: postgres://solana:${DB_PASSWORD}@db/solana
    build:
      context: .
      dockerfile: Migrator.Dockerfile
    volumes:
      - ./init.sql:/init.sql

  db:
    image: "postgres:14"
    restart: always
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr", "-c", "max_connections=200" ]
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: solana # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: ${DB_PASSWORD} # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: solana
    volumes:
      - ${DB_VOLUME}:/var/lib/postgresql/data/:rw

  solana:
      image: das-geyser-grpc
      container_name: solana
      volumes:
        - ./programs:/so/:ro
        - ./ledger:/config:rw
        - ./solana-test-validator-geyser-config:/plugin-config:rw
        - ./runs.sh:/runs.sh
      environment:
        RUST_LOG: error
        PLUGIN_MESSENGER_CONFIG.messenger_type: "Redis"
        PLUGIN_MESSENGER_CONFIG.connection_config: '{redis_connection_str="redis://redis"}'
      # deploy:
      #   resources:
      #     limits:
      #       cpus: '0.5'
      #       memory: 2G
      #     reservations:
      #       cpus: '0.0001'
      #       memory: 20M
      ports:
        - "9098:8899"
        - "9099:8900"
        - "9092:8900"

  ingester:
    depends_on:
      - migrator
      - builder
      - redis
      - db
    restart: always
    environment:
      RUST_LOG: error
      CARGO_PKG_NAME: ingester
    build:
      context: .
      dockerfile: Ingest.Dockerfile
    volumes:
      - ./solana-test-validator-geyser-config/config-ingester.yml:/config.yml
    command: --config /config.yml ingester
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-size: 200k
        max-file: 10
        
  grpc2redis:
    depends_on:
      - redis
      - builder
    restart: always
    environment:
      RUST_LOG: error
      CARGO_PKG_NAME: grpc2redis
    build:
      context: .
      dockerfile: Ingest.Dockerfile
    volumes:
      - ./solana-test-validator-geyser-config/config-grpc2redis.yml:/config.yml
    command: --config /config.yml grpc2redis
    logging:
      driver: "json-file"
      options:
        max-size: 200k
        max-file: 10

  download-metadata:
    depends_on:
      - migrator
      - builder
      - db
    restart: always
    environment:
      RUST_LOG: error
      CARGO_PKG_NAME: download-metadata
    build:
      context: .
      dockerfile: Ingest.Dockerfile
    volumes:
      - ./solana-test-validator-geyser-config/config-download-metadata.yml:/config.yml
    command: --config /config.yml download-metadata
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-size: 200k
        max-file: 10


  prometheus:
    image: prom/prometheus
    ports:
      - ${PROMETHEUS_PORT}:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/rules/rules.yml:/etc/prometheus/rules/rules.yml
      - das_prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=7d'
    restart: unless-stopped

  grafana:
    image: docker.io/grafana/grafana:latest
    ports:
      - ${GRAFANA_PORT}:3000
    volumes:
      - das_grafana_data:/var/lib/grafana
    restart: unless-stopped
    depends_on:
      - prometheus

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    command:
      - '--housekeeping_interval=55s'
      - '--docker_only=true'
      # - '--disable_metrics=disk,network,tcp,udp,percpu,sched,process'
    # ports:
    #   - '8083:8080'
    volumes:
      # linux
      - /:/rootfs:ro # Needed for root file system access (even though it won't work fully on Windows)
      - /run:/run:ro # System access (won't work fully on Windows but needed)
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      # windows
      # - /:/rootfs:ro 
      # - /var/run:/var/run:ro # Access to Docker's API on Windows
      # - /sys:/sys:ro 
      # - /c/ProgramData/docker:/var/lib/docker:ro # Windows Docker directory
    devices:
      - /dev/kmsg

  alertmanager:
    image: quay.io/prometheus/alertmanager:latest
    ports:
      - ${ALERTMANAGER_PORT}:9093
    volumes:
      - ./prometheus/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager_data:/data
    restart: unless-stopped
    depends_on:
      - prometheus

volumes:
  das_prometheus_data:
  das_grafana_data:
  alertmanager_data:
