route:
  receiver: "email"
  repeat_interval: 4h
  group_by: [alertname]

receivers:
  - name: "email"
    email_configs:
      - to: "tanveer.khan2692000@gmail.com,aetozi@honeycombprotocol.com,mustafa@honeycombprotocol.com,shayan@honeycombprotocol.com,sultan@honeycombprotocol.com" # Recipient email address
        from: "tanveer@honeycombprotocol.com" # Sender email address (same as smtp_from)
        smarthost: "smtp.gmail.com:587" # SMTP server and port (same as smtp_smarthost)
        auth_username: "tanveer@honeycombprotocol.com" # SMTP auth username (same as smtp_auth_username)
        auth_password: "ertnhavkeublqqgr" # SMTP auth password (same as smtp_auth_password)
        require_tls: true
        tls_config:
          insecure_skip_verify: true
