prometheus: 127.0.0.1:8874
redis:
  url: redis://redis:6379
  group: ingester
  consumer: backfill # every new ingester instance should have uniq name
  streams:
    - type: transaction
      stream: TXN_FILL
      data_key: data
      xack_batch_max_size: 100
      xack_batch_max_idle_ms: 10
      xack_max_in_process: 100
  prefetch_queue_size: 1_000 # max number of messages available in the read queue for processing
  xpending_max: 250 # used for reading pending messages
  xpending_only: false # exit once all pending messages consumed (should be applied if you want downscale number of ingesters)
  xreadgroup_max: 1_000 # applied per each stream in one request
postgres:
  url: postgres://solana:solana@db/solana
  min_connections: 10
  max_connections: 50 # `max_connection` should be bigger than `program_transformer.max_tasks_in_process` otherwise unresolved lock is possible
program_transformer:
  transactions_cl_audits: false
  max_tasks_in_process: 40
download_metadata:
  max_attempts: 3
inactivity_timeout_sec: 120
